### ISSUE TITLE
video and audio desynchronized

### ISSUE THREAD

**Issue by egradman** [wgryc/video-input-js#2]
I love this and I want to use it!

Just tried the demo.  During playback, the video and audio desynchronized by what sounded like at least 750ms.

```
Google Chrome | 86.0.4240.193 (Official Build) (x86_64)
Revision | 4b1dc838fc8d2b55f2147e7a642b20baf443da5c-refs/branch-heads/4240@{#1411}
OS | macOS Version 10.14.6 (Build 18G1012)
JavaScript | V8 8.6.395.24
```

**Comment by wgryc** [comment]
Thanks so much for this. Could you try running this official WebRTC demo as well?
https://webrtc.github.io/samples/src/content/getusermedia/record/

Does it happen there too?

**Comment by wgryc** [comment]
Since I haven't heard back, I'll close the issue. Hopefully this is working for you!
